import { Recipe } from '../../src/types';

export const NEW_BREADS_RECIPES: Recipe[] = [
  {
    id: "kn-breads-581",
    title: "Pão de Forma Cetogênico Multigrãos com Psyllium, Amêndoas e Linhaça",
    description: "Pão artesanal estruturado que cresce com miolo macio e elástico, perfeito para fatiar, tostar na torradeira e fazer sanduíches.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    category: "breads",
    subcategory: "pães de forma",
    categoryName: "Pães e Massas",
    difficulty: "Médio",
    prepTime: 15,
    cookTime: 45,
    servings: 10,
    rating: 5.0,
    reviewCount: 82,
    isPremium: true,
    isPopular: true,
    isNew: true,
    tags: ["pão keto", "psyllium", "multigrãos", "sem glúten", "café da manhã"],
    nutrition: { calories: 190, protein: 8, netCarbs: 2, fat: 16, fiber: 5, carbs: 7 },
    ingredients: [
      { id: "kn-br581-1", name: "Farinha de amêndoas pura", amount: "200 g", quantity: 200, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br581-2", name: "Psyllium em pó puro (husk)", amount: "40 g", quantity: 40, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br581-3", name: "Farinha de linhaça dourada moída", amount: "30 g", quantity: 30, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br581-4", name: "Claras de ovos caipiras", amount: "5 unidades (150 g)", quantity: 150, unit: "g", optional: false, category: "Proteínas" },
      { id: "kn-br581-5", name: "Água fervente filtrada", amount: "220 ml", quantity: 220, unit: "ml", optional: false, category: "Despensa" },
      { id: "kn-br581-6", name: "Vinagre de maçã", amount: "2 colheres de sopa", quantity: 30, unit: "ml", optional: false, category: "Despensa" },
      { id: "kn-br581-7", name: "Fermento químico em pó e sal marinho", amount: "1 colher de sopa", quantity: 15, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br581-8", name: "Mix de sementes (gergelim e girassol) para o topo", amount: "20 g", quantity: 20, unit: "g", optional: false, category: "Despensa" }
    ],
    steps: [
      { stepNumber: 1, instruction: "Misturar os secos: Em um bowl grande, misture bem a farinha de amêndoas, o psyllium, a linhaça, o sal e o fermento.", timerSeconds: 60 },
      { stepNumber: 2, instruction: "Adicionar claras e vinagre: Junte as claras de ovos e o vinagre de maçã batendo com batedeira por 1 minuto.", timerSeconds: 60 },
      { stepNumber: 3, instruction: "Água fervente e sova: Despeje a água fervente de uma vez só e continue batendo vigorosamente por 2 minutos. O psyllium absorverá o líquido criando uma massa elástica parecida com pão tradicional.", timerSeconds: 120, tip: "A água DEVE estar fervendo para ativar as fibras expansoras do psyllium." },
      { stepNumber: 4, instruction: "Assar na forma de bolo inglês: Coloque em forma untada, salpique as sementes no topo e asse a 180°C por 45 a 50 minutos até soar oco ao bater no fundo." }
    ],
    chefTip: "Deixe o pão esfriar completamente sobre uma grade antes de cortar a primeira fatia; o corte com ele quente soltará vapor e condensará o miolo."
  },
  {
    id: "kn-breads-582",
    title: "Pão de Queijo Mineiro Cetogênico com Polvilho Zero à Base de Muçarela e Parmesão",
    description: "Casquinha estaladiça dourada e puxa-puxa interno irresistível, feito sem nenhum grão de polvilho usando a técnica de queijos nobres.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    category: "breads",
    subcategory: "pães de queijo",
    categoryName: "Pães e Massas",
    difficulty: "Fácil",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    rating: 5.0,
    reviewCount: 91,
    isPremium: false,
    tags: ["pão de queijo", "mineiro", "air fryer", "café com queijo", "zero polvilho"],
    nutrition: { calories: 230, protein: 14, netCarbs: 1, fat: 19, fiber: 1, carbs: 2 },
    ingredients: [
      { id: "kn-br582-1", name: "Queijo muçarela ralado fino", amount: "180 g", quantity: 180, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br582-2", name: "Queijo minas padrão ou canastra curado ralado", amount: "80 g", quantity: 80, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br582-3", name: "Farinha de amêndoas fina", amount: "40 g", quantity: 40, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br582-4", name: "Ovo caipira batido", amount: "1 unidade", quantity: 1, unit: "unidade", optional: false, category: "Proteínas" },
      { id: "kn-br582-5", name: "Cream cheese tradicional", amount: "30 g", quantity: 30, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br582-6", name: "Fermento em pó e sal a gosto", amount: "1 colher de chá", quantity: 5, unit: "g", optional: false, category: "Despensa" }
    ],
    steps: [
      { stepNumber: 1, instruction: "Derreter a base: Em tigela de vidro, derreta a muçarela com o cream cheese no micro-ondas por 50 segundos até virar massa única.", timerSeconds: 60 },
      { stepNumber: 2, instruction: "Formar a massa: Junte o ovo batido, o queijo minas curado, a farinha de amêndoas e o fermento, sovando rapidamente até incorporar.", timerSeconds: 120 },
      { stepNumber: 3, instruction: "Modelar bolinhas: Unte as mãos com azeite e faça 10 a 12 bolinhas uniformes.", timerSeconds: 120 },
      { stepNumber: 4, instruction: "Assar na air fryer ou forno: Asse na air fryer a 180°C por 12 a 15 minutos até dourarem intensamente e inflarem." }
    ],
    chefTip: "O queijo canastra curado confere a picância e o perfume autêntico das fazendas mineiras a cada mordida."
  },
  {
    id: "kn-breads-583",
    title: "Pizza Marguerita com Massa Fathead Crocante de Queijo e Farinha de Amêndoas",
    description: "A clássica massa italiana fathead crocante com molho de tomate pelado, muçarela de búfala derretida e manjericão fresco.",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    category: "breads",
    subcategory: "pizzas keto",
    categoryName: "Pães e Massas",
    difficulty: "Médio",
    prepTime: 15,
    cookTime: 12,
    servings: 3,
    rating: 5.0,
    reviewCount: 95,
    isPremium: true,
    tags: ["pizza", "fathead", "marguerita", "crocante", "jantar de sexta"],
    nutrition: { calories: 420, protein: 26, netCarbs: 3, fat: 34, fiber: 2, carbs: 5 },
    ingredients: [
      { id: "kn-br583-1", name: "Queijo muçarela ralado (massa)", amount: "200 g", quantity: 200, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br583-2", name: "Farinha de amêndoas pura", amount: "90 g", quantity: 90, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br583-3", name: "Cream cheese ou requeijão de corte", amount: "30 g", quantity: 30, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br583-4", name: "Ovo inteiro batido", amount: "1 unidade", quantity: 1, unit: "unidade", optional: false, category: "Proteínas" },
      { id: "kn-br583-5", name: "Molho de tomate pelado rústico sem açúcar", amount: "60 g", quantity: 60, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br583-6", name: "Muçarela de búfala fresca fatiada", amount: "120 g", quantity: 120, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br583-7", name: "Folhas frescas de manjericão e azeite", amount: "1 punhado", quantity: 10, unit: "g", optional: false, category: "Temperos" }
    ],
    steps: [
      { stepNumber: 1, instruction: "Massa fathead: Derreta a muçarela e o cream cheese no micro-ondas por 1 minuto. Misture a farinha de amêndoas e o ovo até formar uma bola lisa.", timerSeconds: 180 },
      { stepNumber: 2, instruction: "Abrir a massa: Abra a massa entre duas folhas de papel manteiga usando um rolo até espessura de 4mm.", timerSeconds: 120 },
      { stepNumber: 3, instruction: "Pré-assar a base: Fure a massa com um garfo e asse no forno a 210°C por 8 minutos até dourar e firmar.", timerSeconds: 480, tip: "Pré-assar a base é o segredo para a pizza não amolecer com o molho." },
      { stepNumber: 4, instruction: "Rechear e gratinar: Espalhe o molho, disponha as fatias de muçarela de búfala e volte ao forno por 5 minutos até o queijo borbulhar. Finalize com manjericão fresco." }
    ],
    chefTip: "Abrir a massa entre duas folhas de papel manteiga impede que o queijo grude no rolo e dispensa qualquer acréscimo de farinha."
  },
  {
    id: "kn-breads-584",
    title: "Focaccia de Ervas Aromáticas com Azeite Extravirgem, Alecrim e Flor de Sal",
    description: "Pão achatado italiano aromático com crosta dourada e pequenas cavidades ricas em azeite, alecrim e azeitonas pretas.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    category: "breads",
    subcategory: "focaccias",
    categoryName: "Pães e Massas",
    difficulty: "Fácil",
    prepTime: 12,
    cookTime: 20,
    servings: 6,
    rating: 4.9,
    reviewCount: 46,
    isPremium: true,
    tags: ["focaccia", "azeite", "alecrim", "italiano", "antepasto"],
    nutrition: { calories: 250, protein: 9, netCarbs: 2, fat: 23, fiber: 3, carbs: 5 },
    ingredients: [
      { id: "kn-br584-1", name: "Farinha de amêndoas fina", amount: "150 g", quantity: 150, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br584-2", name: "Queijo muçarela derretido", amount: "150 g", quantity: 150, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br584-3", name: "Ovos caipiras inteiros", amount: "2 unidades", quantity: 2, unit: "unidade", optional: false, category: "Proteínas" },
      { id: "kn-br584-4", name: "Azeite de oliva extravirgem nobre", amount: "4 colheres de sopa", quantity: 60, unit: "ml", optional: false, category: "Despensa" },
      { id: "kn-br584-5", name: "Folhas de alecrim fresco e alho laminado", amount: "2 colheres de sopa", quantity: 15, unit: "g", optional: false, category: "Temperos" },
      { id: "kn-br584-6", name: "Azeitonas pretas fatiadas e flor de sal", amount: "40 g", quantity: 40, unit: "g", optional: false, category: "Despensa" }
    ],
    steps: [
      { stepNumber: 1, instruction: "Massa aromática: Derreta a muçarela e sove com os ovos, a farinha de amêndoas e 1 colher de azeite até homogeneizar.", timerSeconds: 180 },
      { stepNumber: 2, instruction: "Espalhar na assadeira: Espalhe a massa numa assadeira forrada com papel manteiga com cerca de 1,5cm de altura.", timerSeconds: 120 },
      { stepNumber: 3, instruction: "Fazer as covinhas: Com as pontas dos dedos embebidas em azeite, faça covinhas em toda a superfície.", timerSeconds: 60 },
      { stepNumber: 4, instruction: "Assar no forno: Regue com o azeite restante, espalhe o alecrim, o alho e as azeitonas com flor de sal. Asse a 190°C por 20 minutos até dourar intensamente." }
    ],
    chefTip: "O azeite nas covinhas penetra na massa durante o forno, garantindo a maciez e o aroma típico das padarias italianas."
  },
  {
    id: "kn-breads-585",
    title: "Nhoque Cetogênico de Ricota com Espinafre e Manteiga de Sálvia Queimada",
    description: "Pequenas nuvens macias feitas de ricota prensada, espinafre e parmesão curado, salteadas em manteiga noisette de sálvia crocante.",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
    category: "breads",
    subcategory: "massas frescas",
    categoryName: "Pães e Massas",
    difficulty: "Médio",
    prepTime: 20,
    cookTime: 8,
    servings: 2,
    rating: 4.9,
    reviewCount: 53,
    isPremium: true,
    tags: ["nhoque", "gnocchi", "ricota", "sálvia", "massa fresca"],
    nutrition: { calories: 340, protein: 18, netCarbs: 3, fat: 28, fiber: 2, carbs: 5 },
    ingredients: [
      { id: "kn-br585-1", name: "Ricota fresca de qualidade bem drenada e seca", amount: "250 g", quantity: 250, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br585-2", name: "Espinafre cozido e espremido até secar", amount: "100 g", quantity: 100, unit: "g", optional: false, category: "Vegetais" },
      { id: "kn-br585-3", name: "Gema de ovo caipira", amount: "1 unidade", quantity: 1, unit: "unidade", optional: false, category: "Proteínas" },
      { id: "kn-br585-4", name: "Queijo parmesão ralado finíssimo", amount: "50 g", quantity: 50, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br585-5", name: "Farinha de amêndoas para dar o ponto", amount: "30 g", quantity: 30, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br585-6", name: "Manteiga sem sal e folhas frescas de sálvia", amount: "35 g", quantity: 35, unit: "g", optional: false, category: "Despensa" }
    ],
    steps: [
      { stepNumber: 1, instruction: "Secar ricota e espinafre: Pressione a ricota e o espinafre com pano de prato até não restar nenhuma umidade.", timerSeconds: 180 },
      { stepNumber: 2, instruction: "Massa do nhoque: Misture a ricota, espinafre picado, a gema, o parmesão, a farinha de amêndoas e noz-moscada ralada.", timerSeconds: 120 },
      { stepNumber: 3, instruction: "Modelar rolinhos: Modele rolos finos e corte em pedaços de 2cm.", timerSeconds: 180 },
      { stepNumber: 4, instruction: "Dourar na manteiga de sálvia: Em frigideira larga, derreta a manteiga com as folhas de sálvia até a manteiga começar a dourar (noisette). Coloque os nhoques e doure por 3 minutos de cada lado." }
    ],
    chefTip: "Não ferva esse nhoque em água; doure diretamente na manteiga de sálvia para manter o formato perfeito e crosta crocante."
  },
  {
    id: "kn-breads-586",
    title: "Panquecas Americanas Cetogênicas Fofinhas com Creme de Amêndoas e Manteiga",
    description: "Pilhas de panquecas altas e macias preparadas com farinha de amêndoas e cream cheese, servidas com calda zero e manteiga derretida.",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    category: "breads",
    subcategory: "panquecas",
    categoryName: "Pães e Massas",
    difficulty: "Fácil",
    prepTime: 8,
    cookTime: 10,
    servings: 2,
    rating: 4.8,
    reviewCount: 62,
    isPremium: false,
    tags: ["panqueca", "café americano", "fofinha", "brunch", "rápido"],
    nutrition: { calories: 290, protein: 12, netCarbs: 2, fat: 26, fiber: 2, carbs: 4 },
    ingredients: [
      { id: "kn-br586-1", name: "Ovos caipiras inteiros", amount: "2 unidades", quantity: 2, unit: "unidade", optional: false, category: "Proteínas" },
      { id: "kn-br586-2", name: "Cream cheese tradicional", amount: "60 g", quantity: 60, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br586-3", name: "Farinha de amêndoas", amount: "40 g", quantity: 40, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br586-4", name: "Adoçante eritritol", amount: "1 colher de sopa", quantity: 15, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br586-5", name: "Fermento químico em pó e baunilha", amount: "1 colher de chá", quantity: 5, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br586-6", name: "Manteiga para dourar", amount: "15 g", quantity: 15, unit: "g", optional: false, category: "Despensa" }
    ],
    steps: [
      { stepNumber: 1, instruction: "Bater a massa: No liquidificador ou mixer, bata os ovos com o cream cheese, a farinha de amêndoas, o eritritol, o fermento e a baunilha por 1 minuto.", timerSeconds: 60 },
      { stepNumber: 2, instruction: "Frigideira untada: Aqueça uma frigideira antiaderente untada com manteiga em fogo baixo.", timerSeconds: 60 },
      { stepNumber: 3, instruction: "Dourar os discos: Despeje conchas pequenas de massa. Quando formarem bolhinhas no topo (cerca de 2 minutos), vire com cuidado e doure por mais 1 minuto.", timerSeconds: 180 },
      { stepNumber: 4, instruction: "Servir a pilha: Empilhe as panquecas e coloque uma noz generosa de manteiga para derreter por cima." }
    ],
    chefTip: "Manter o fogo no mínimo é crucial para as panquecas cozinharem no centro sem queimar a crosta exterior."
  },
  {
    id: "kn-breads-587",
    title: "Tortilhas Flexíveis Cetogênicas com Farinha de Coco e Psyllium para Wraps",
    description: "Discos maleáveis que dobram perfeitamente sem quebrar, ideais para tacos mexicanos, wraps de salada e sanduíches enrolados.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    category: "breads",
    subcategory: "massas frescas",
    categoryName: "Pães e Massas",
    difficulty: "Fácil",
    prepTime: 10,
    cookTime: 6,
    servings: 3,
    rating: 4.8,
    reviewCount: 39,
    isPremium: false,
    tags: ["tortilha", "wrap", "taco", "farinha de coco", "maleável"],
    nutrition: { calories: 150, protein: 4, netCarbs: 2, fat: 11, fiber: 5, carbs: 7 },
    ingredients: [
      { id: "kn-br587-1", name: "Farinha de coco pura fina", amount: "50 g", quantity: 50, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br587-2", name: "Psyllium husk em pó fino", amount: "15 g", quantity: 15, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br587-3", name: "Azeite de oliva extravirgem", amount: "2 colheres de sopa", quantity: 30, unit: "ml", optional: false, category: "Despensa" },
      { id: "kn-br587-4", name: "Água morna temperada com sal", amount: "120 ml", quantity: 120, unit: "ml", optional: false, category: "Despensa" },
      { id: "kn-br587-5", name: "Fermento químico em pó", amount: "1 colher de chá", quantity: 3, unit: "g", optional: false, category: "Despensa" }
    ],
    steps: [
      { stepNumber: 1, instruction: "Hidratar e amassar: Misture os secos, adicione o azeite e a água morna, sovando com as mãos até formar uma massa macia e homogênea. Deixe descansar por 5 minutos.", timerSeconds: 300 },
      { stepNumber: 2, instruction: "Abrir os discos: Divida em 4 bolinhas e abra entre duas folhas de filme plástico com um rolo até espessura bem fina.", timerSeconds: 180 },
      { stepNumber: 3, instruction: "Tostar na frigideira seca: Aqueça frigideira antiaderente sem óleo e toste a tortilha por 1 minuto e meio de cada lado até formar pontinhos tostados.", timerSeconds: 180 },
      { stepNumber: 4, instruction: "Manter macia: Guarde as tortilhas prontas embrulhadas em um pano de prato úmido para manter a flexibilidade." }
    ],
    chefTip: "O psyllium confere a elasticidade que permite enrolar a tortilha como wrap sem que ela parta ou esfarele."
  },
  {
    id: "kn-breads-588",
    title: "Pão de Alho Rústico com Baguete Cetogênica e Pasta Cremosa de Parmesão",
    description: "Baguete de amêndoas fatiada em gomos recheados com pasta intensa de manteiga, alho triturado, queijo parmesão e cheiro-verde.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    category: "breads",
    subcategory: "pães de forma",
    categoryName: "Pães e Massas",
    difficulty: "Fácil",
    prepTime: 12,
    cookTime: 10,
    servings: 4,
    rating: 5.0,
    reviewCount: 76,
    isPremium: false,
    tags: ["pão de alho", "churrasco", "parmesão", "air fryer", "crocante"],
    nutrition: { calories: 290, protein: 11, netCarbs: 2, fat: 26, fiber: 2, carbs: 4 },
    ingredients: [
      { id: "kn-br588-1", name: "Pão baguete cetogênico assado", amount: "1 unidade (250 g)", quantity: 250, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br588-2", name: "Manteiga em ponto de pomada", amount: "50 g", quantity: 50, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br588-3", name: "Requeijão cremoso ou maionese caseira", amount: "50 g", quantity: 50, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br588-4", name: "Dentes de alho triturados", amount: "4 unidades", quantity: 15, unit: "g", optional: false, category: "Temperos" },
      { id: "kn-br588-5", name: "Queijo parmesão e muçarela ralados", amount: "80 g", quantity: 80, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br588-6", name: "Cheiro-verde picadinho e orégano", amount: "2 colheres de sopa", quantity: 10, unit: "g", optional: false, category: "Temperos" }
    ],
    steps: [
      { stepNumber: 1, instruction: "Pasta de alho: Em um bowl, misture a manteiga, o requeijão, o alho triturado, metade do parmesão e o cheiro-verde.", timerSeconds: 120 },
      { stepNumber: 2, instruction: "Fatiar a baguete: Faça cortes transversais na baguete a cada 2cm sem cortar a casca inferior até o fim.", timerSeconds: 120 },
      { stepNumber: 3, instruction: "Rechear os gomos: Espalhe a pasta generosamente dentro de cada fenda do pão e cubra o topo com o restante do queijo.", timerSeconds: 180 },
      { stepNumber: 4, instruction: "Gratinar na air fryer ou forno: Asse a 200°C por 8 a 10 minutos até o queijo borbulhar dourado e o pão estalar de crocante." }
    ],
    chefTip: "O segredo de churrascaria é misturar a manteiga com requeijão para a pasta não ressecar com o calor do fogo."
  },
  {
    id: "kn-breads-589",
    title: "Lasanha Cetogênica com Lâminas de Palmito Pupunha e Bolonhesa Rústica",
    description: "Camadas generosas de molho bolonhesa encorpado, lâminas de palmito pupunha cozidas, queijo muçarela e molho branco de nata.",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
    category: "breads",
    subcategory: "massas frescas",
    categoryName: "Pães e Massas",
    difficulty: "Médio",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    rating: 4.9,
    reviewCount: 58,
    isPremium: true,
    tags: ["lasanha", "palmito pupunha", "bolonhesa", "gratinado", "confort food"],
    nutrition: { calories: 430, protein: 34, netCarbs: 4, fat: 31, fiber: 3, carbs: 7 },
    ingredients: [
      { id: "kn-br589-1", name: "Lâminas largas de palmito pupunha fresco para lasanha", amount: "400 g", quantity: 400, unit: "g", optional: false, category: "Vegetais" },
      { id: "kn-br589-2", name: "Molho bolonhesa de carne moída com tomate", amount: "400 g", quantity: 400, unit: "g", optional: false, category: "Carnes" },
      { id: "kn-br589-3", name: "Queijo muçarela fatiado", amount: "180 g", quantity: 180, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br589-4", name: "Nata fresca batida com parmesão (molho branco)", amount: "120 g", quantity: 120, unit: "g", optional: false, category: "Laticínios" },
      { id: "kn-br589-5", name: "Orégano fresco e queijo parmesão ralado", amount: "40 g", quantity: 40, unit: "g", optional: false, category: "Laticínios" }
    ],
    steps: [
      { stepNumber: 1, instruction: "Amolecer o pupunha: Cozinhe as lâminas de pupunha no vapor por 5 minutos para amaciar as fibras.", timerSeconds: 300 },
      { stepNumber: 2, instruction: "Montar as camadas: Em refratário médio, faça uma camada de bolonhesa, cubra com lâminas de pupunha, muçarela e molho branco.", timerSeconds: 240 },
      { stepNumber: 3, instruction: "Repetir até o topo: Repita as camadas finalizando com muçarela e parmesão ralado na última camada.", timerSeconds: 120 },
      { stepNumber: 4, instruction: "Assar no forno: Leve ao forno pré-aquecido a 200°C por 20 a 25 minutos até o topo dourar com manchas tostadas de gratinado." }
    ],
    chefTip: "O pupunha mantém a estrutura firme ao assar, sem desmilinguir como a abobrinha, gerando fatias perfeitas no prato."
  },
  {
    id: "kn-breads-590",
    title: "Pão Australiano Cetogênico Escuro com Cacau 100% e Manteiga Melada de Eritritol",
    description: "Pão aromático adocicado com toque de cacau e especiarias, servido quentinho com a famosa manteiga batida.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    category: "breads",
    subcategory: "pães de forma",
    categoryName: "Pães e Massas",
    difficulty: "Médio",
    prepTime: 15,
    cookTime: 40,
    servings: 8,
    rating: 4.9,
    reviewCount: 61,
    isPremium: true,
    tags: ["pão australiano", "cacau", "manteiga melada", "outback", "pão escuro"],
    nutrition: { calories: 220, protein: 9, netCarbs: 3, fat: 19, fiber: 4, carbs: 7 },
    ingredients: [
      { id: "kn-br590-1", name: "Farinha de amêndoas pura", amount: "180 g", quantity: 180, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br590-2", name: "Psyllium em pó e linhaça dourada", amount: "40 g", quantity: 40, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br590-3", name: "Cacau em pó 100% alcalino (para a cor escura)", amount: "2 colheres de sopa", quantity: 20, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br590-4", name: "Adoçante eritritol e café solúvel", amount: "2 colheres de sopa", quantity: 25, unit: "g", optional: false, category: "Despensa" },
      { id: "kn-br590-5", name: "Claras batidas e água fervente", amount: "180 ml", quantity: 180, unit: "ml", optional: false, category: "Despensa" },
      { id: "kn-br590-6", name: "Manteiga batida com toque de canela e eritritol", amount: "60 g", quantity: 60, unit: "g", optional: false, category: "Despensa" }
    ],
    steps: [
      { stepNumber: 1, instruction: "Secos aromáticos: Misture a farinha de amêndoas, psyllium, linhaça, cacau em pó, café solúvel, eritritol e sal.", timerSeconds: 60 },
      { stepNumber: 2, instruction: "Hidratação quente: Adicione as claras e a água fervente batendo com a batedeira até virar massa escura elástica.", timerSeconds: 120 },
      { stepNumber: 3, instruction: "Modelar o filão: Modele o pão em formato de filão rústico e faça cortes superficiais no topo com uma lâmina afiada.", timerSeconds: 120 },
      { stepNumber: 4, instruction: "Assar no forno: Asse a 180°C por 40 minutos. Sirva fatias mornas acompanhadas da manteiga batida com eritritol e canela." }
    ],
    chefTip: "O café solúvel com o cacau alcalino intensifica a cor bronzeada profunda sem deixar gosto de café no pão pronto."
  }
];
